sonar.organization=frarthur
sonar.projectKey=frarthur_Hypocaps_web

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,**/coverage/**,**/src/stories/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
